# SITE CONFIGURATION
baseurl: ""
url: "https://binaryresearch.github.io"
title: Binary Research # site's title
description: "binary analysis, reverse engineering, security research, machine learning" # used by search engines

defaults:
  - 
    scope:
      path: "" # an empty string here means all files in the project
    values:
      image: assets/img/julian-avatar.jpg # seo tag

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  avatar: assets/img/julian-avatar.jpg
  color_image: /assets/img/juhani-jokinen-1.jpg # In post when you set color
  favicon: assets/favicon.ico

  # Header and footer text
  header_text: Delving Deeper into the Mysteries of the Machine
  header_feature_image: assets/img/juhani-jokinen-1.jpg
  footer_text: made by julian

  # Icons
  rss: true  # Make sure you created a feed.xml with feed.xml layout
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab:
  github: "binaryresearch"
  google_plus:
  instagram:
  keybase:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  "https://reverseengineering.stackexchange.com/users/18317/julian?tab=profile" # Full URL
  steam:
  tumblr:
  twitter: # "_SYS_V"
  vimeo:
  wordpress:
  youtube:

  # Sharing options
  share_buttons:
    facebook: true
    twitter: true
    tumblr:
    pinterest:
    pocket:
    reddit: true
    linkedin: true
    wordpress: true
    email: true

  # Scripts / Features 
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_share_on: "Share on"
  str_add_to: "Add to"
  str_email: "Email"
  str_tweet: "Tweet"
  str_pin_it: "Pin it"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."

  # Post navigation
  post_navigation: true

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# PAGINATION
paginate: 10
paginate_path: "blog/page:num"

# EXCERPTS
//excerpt_separator: <!--more-->

# AUTHORS
authors:
  julian: # author-id
    name: julian
    avatar: "assets/img/avatars/julian_avatar.jpg"
    url: "https://github.com/binaryresearch"
#  sylhare:
#    name: Sylhare
#    avatar: "assets/img/avatars/sylhare_avatar.png"
#    url: "https://github.com/sylhare"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag]
exclude: [".jekyll-cache", "Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", ".idea",
          "LICENSE", "README.md", "screenshot.png", "assets/package.json", "assets/node_modules", "assets/gulpfile.js"]
# theme: type-on-strap # Uncomment if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap # If using as a remote_theme in github
